import { useCallback, useEffect, useRef, useState } from "react";
import { WebContainer } from "@webcontainer/api";

import { buildFileTree, getFilePath } from "@/features/preview/utils/file-tree";
import { useFiles } from "@/features/projects/hooks/use-files";

import { Id } from "../../../../convex/_generated/dataModel";

// Singleton variables to manage the WebContainer lifecycle
// and prevent multiple simultaneous boot attempts
let webcontainerInstance: WebContainer | null = null;
let bootPromise: Promise<WebContainer> | null = null;

const getWebContainer = async (): Promise<WebContainer> => {
  // Return the existing WebContainer instance immediately if it's already booted
  if (webcontainerInstance) return webcontainerInstance;

  // If a boot process is not already running, initiate a new WebContainer boot promise
  if (!bootPromise) {
    bootPromise = WebContainer.boot({ coep: "credentialless" });
  }

  // Wait for the boot promise to resolve and store the active instance
  webcontainerInstance = await bootPromise;

  // Return the fully booted WebContainer instance for use
  return webcontainerInstance;
};

//Destroys the WebContainer instance to not have any memory leaks, turning it unusable,and releases its resources.
//After this, a new WebContainer instance can be obtained by calling
const teardownWebContainer = async () => {
  //wait for the boot if it's still running
  if (bootPromise) {
    try {
      webcontainerInstance = await bootPromise;
    } catch {
      webcontainerInstance = null;
    }
  }
  if (webcontainerInstance) {
    webcontainerInstance.teardown();
    webcontainerInstance = null;
  }
  bootPromise = null;
};

interface UseWebContainerProps {
  projectId: Id<"projects">;
  enabled: boolean;
  settings?: {
    installCommand?: string;
    devCommand?: string;
  };
}

// How long the incoming `files` list has to stay unchanged before we treat
// it as "settled" and safe to boot/mount. This is a safety net for the case
// where the agent is still streaming files in when `enabled` flips true.
// Prefer wiring `enabled` to an actual "generation completed" flag when one
// is available instead of relying on this timer.
const SETTLE_DELAY_MS = 800;

export const useWebContainer = ({
  projectId,
  enabled,
  settings,
}: UseWebContainerProps) => {
  // Track the current lifecycle status of the WebContainer instance
  const [status, setStatus] = useState<
    "idle" | "booting" | "installing" | "running" | "error"
  >("idle");

  // Store the live preview URL generated by the WebContainer
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  // Store any error messages that occur during the boot or execution process
  const [error, setError] = useState<string | null>(null);
  // A key used to force a restart or remount of the WebContainer when updated
  const [restartKey, setRestartKey] = useState(0);
  //reload the i frame on change
  const [reloadKey, setReloadKey] = useState(0);
  // Store the accumulated terminal output logs from running commands
  const [terminalOutput, setTerminalOutput] = useState("");
  // Reference to hold the active WebContainer instance across renders without triggering updates
  const containerRef = useRef<WebContainer | null>(null);
  // Flag to track whether the boot sequence has already been initiated to prevent duplicates
  const hasStartedRef = useRef(false);
  // Tracks the last-written content per file path so the sync effect only
  // writes files that actually changed, instead of rewriting everything
  // on every files update.
  const syncedRef = useRef(new Map<string, string>());
  // Whether the current `files` snapshot has stopped changing for
  // SETTLE_DELAY_MS. We refuse to boot/mount until this is true so we don't
  // mount a partial tree while the agent is still writing files.
  const [settled, setSettled] = useState(false);

  // Fetch files in real-time from Convex; changes automatically sync to the WebContainer via fs.writeFile without a full reload
  const files = useFiles(projectId);

  // Debounce "settled" state off of the files reference. Every time `files`
  // changes we consider the snapshot unsettled again and restart the timer.
  useEffect(() => {
    setSettled(false);
    if (!files || files.length === 0) return;
    const t = setTimeout(() => setSettled(true), SETTLE_DELAY_MS);
    return () => clearTimeout(t);
  }, [files]);

  useEffect(() => {
    if (status !== "running") return;
    const t = setTimeout(() => setReloadKey((k) => k + 1), 1500);
    return () => clearTimeout(t);
  }, [files, status]);

  //Initial boot and mount
  useEffect(() => {
    // if the container not enabled, no files, the files snapshot hasn't
    // settled yet, or the container already started - do nothing.
    if (
      !enabled ||
      !files ||
      files.length === 0 ||
      !settled ||
      hasStartedRef.current
    ) {
      return;
    }

    // Mark that the start sequence has been initiated to prevent duplicate boots
    hasStartedRef.current = true;

    // Define an asynchronous function to handle the entire WebContainer boot and setup lifecycle
    const start = async () => {
      try {
        // Update the status state to indicate that the container is currently booting up
        setStatus("booting");
        // Clear any previous error messages from earlier attempts
        setError(null);
        // Reset the terminal output logs to start with a clean slate
        setTerminalOutput("");
        // Clear the sync bookkeeping so we don't skip writes after a restart
        syncedRef.current.clear();

        // Helper function to append new incoming logs/data to the existing terminal output state
        const appendOutput = (data: string) => {
          setTerminalOutput((prev) => prev + data);
        };

        // Call the helper to fetch or boot the singleton WebContainer instance
        const container = await getWebContainer();
        // Store the active WebContainer instance in the ref for later access without re-renders
        containerRef.current = container;
        // Transform the flat list of files fetched from Convex into a nested FileSystemTree object
        const fileTree = buildFileTree(files);
        // Mount the generated file tree directly into the WebContainer instance so it appears in the virtual file system
        await container.mount(fileTree);

        // Seed syncedRef with what we just mounted so the sync effect
        // doesn't immediately rewrite the same content again.
        const filesMap = new Map(files.map((f) => [f._id, f]));
        for (const file of files) {
          if (file.type !== "file" || file.storageId) continue;
          const filePath = getFilePath(file, filesMap);
          syncedRef.current.set(filePath, file.content ?? "");
        }

        // Listen to the 'server-ready' event emitted by the WebContainer when a local development server starts up
        container.on("server-ready", (_port, url) => {
          // Update the preview URL state with the live URL provided by the container
          setPreviewUrl(url);
          // Update the status state to 'running' now that the application is fully up and serving
          setStatus("running");
        });

        // Detect whether this is a plain static project (no package.json at
        // the project root). If so, skip npm install/run and just serve the
        // files directly - there's nothing to install or build.
        const isStaticProject = !files.some(
          (f) => f.type === "file" && f.name === "package.json" && !f.parentId,
        );

        if (isStaticProject) {
          // ---- Static HTML/CSS/JS project: just serve the files ----
          setStatus("installing");
          // reuse status so the UI still shows progress
          appendOutput(`$ npx serve . -l 3000\n`);
          const serveProcess = await container.spawn(
            "npx",
            ["serve", ".", "-l", "3000"],
            // { env: { CI: "true" } },
          );
          serveProcess.output.pipeTo(
            new WritableStream({
              write(data) {
                appendOutput(data);
              },
            }),
          );
        } else {
          // ---- Existing npm install + dev flow ----
          // Update the status state to 'installing' (typically right before running npm install to set up dependencies)
          setStatus("installing");
          // Parse the install command from settings, falling back to "npm install" if not provided
          const installCmd = settings?.installCommand || "npm install";
          // Split the command string into the executable binary (e.g., npm) and its arguments (e.g., install)
          const [installBin, ...installArgs] = installCmd.split(" ");
          // Append the formatted command line to the terminal output log
          appendOutput(`$ ${installCmd}\n`);
          // Spawn a new shell process inside the WebContainer to run the installation command
          const installProcess = await container.spawn(
            installBin,
            installArgs,
            // {
            //   env: { CI: "true" },
            // },
          );
          // Pipe the standard output of the running installation process into a writable stream to capture logs
          installProcess.output.pipeTo(
            new WritableStream({
              // Whenever new data chunks arrive from the process, append them to the terminal output state
              write(data) {
                appendOutput(data);
              },
            }),
          );

          // Await the exit status code of the installation process to see if it succeeded or failed
          const installExitCode = await installProcess.exit;

          // If the exit code is non-zero, it means the installation failed, so throw an error with details
          if (installExitCode !== 0) {
            throw new Error(
              `${installCmd} failed with code ${installExitCode}`,
            );
          }

          // Parse the development command from settings, falling back to "npm run dev" if not provided
          const devCmd = settings?.devCommand || "npm run dev";
          // Split the dev command string into the executable binary (e.g., npm) and its arguments (e.g., run, dev)
          const [devBin, ...devArgs] = devCmd.split(" ");
          // Append a line break and the formatted development command line to the terminal output log
          appendOutput(`\n$ ${devCmd}\n`);
          // Spawn a background process inside the WebContainer to run the development server
          const devProcess = await container.spawn(devBin, devArgs, {
            // env: { CI: "true" },
          });
          // Pipe the standard output logs of the running dev server process into a writable stream
          devProcess.output.pipeTo(
            new WritableStream({
              // Whenever new data chunks stream from the dev server, append them to the terminal output state
              write(data) {
                appendOutput(data);
              },
            }),
          );
        }
        /* Catch any errors that occur during the boot, installation, or server execution process */
      } catch (error) {
        // Extract the error message if it's an Error instance, or fall back to a generic default string
        setError(error instanceof Error ? error.message : "Unknown error");
        // Update the status state to 'error' to indicate that the lifecycle process has failed
        setStatus("error");
      }
    };
    // Invoke the asynchronous start function to trigger the entire WebContainer lifecycle sequence
    start();
  }, [
    enabled,
    files,
    settled,
    restartKey,
    settings?.devCommand,
    settings?.installCommand,
  ]);

  // Synchronizes real-time file updates directly into the WebContainer virtual file system, enabling instant hot-reloading for (source code only).
  useEffect(() => {
    // Grab the current active WebContainer instance from the reference storage
    const container = containerRef.current;
    // Exit early if the container isn't ready yet or files are missing.
    // Allow syncing during "installing" too, not just "running", so files
    // written by the agent while install is still in progress aren't lost.
    if (!container || !files) return;
    if (status !== "running" && status !== "installing") return;

    // Create a Map for fast O(1) lookups of files using their unique IDs as keys
    const filesMap = new Map(files.map((f) => [f._id, f]));

    const sync = async () => {
      // Iterate through every single file in the files collection to check for updates
      for (const file of files) {
        // Skip folders and files backed by storage IDs (not inlined here)
        if (file.type !== "file" || file.storageId) continue;

        const content = file.content ?? "";
        // Resolve the full directory path for the current file using the helper function and map
        const filePath = getFilePath(file, filesMap);

        // Skip files whose content hasn't actually changed since we last wrote them
        if (syncedRef.current.get(filePath) === content) continue;

        try {
          // Make sure the parent directory exists before writing - fs.writeFile
          // does NOT create intermediate directories and fails silently
          // (unhandled rejection) if they're missing.
          const lastSlash = filePath.lastIndexOf("/");
          if (lastSlash > 0) {
            const dir = filePath.slice(0, lastSlash);
            await container.fs.mkdir(dir, { recursive: true });
          }
          // Write or update the file content directly inside the WebContainer's virtual file system in real-time
          await container.fs.writeFile(filePath, content);
          syncedRef.current.set(filePath, content);
        } catch (err) {
          // Surface sync failures instead of swallowing them silently -
          // this is exactly the class of bug that causes "file exists in
          // the tree but not in the container" symptoms.
          console.error(
            "[useWebContainer] failed to sync file:",
            filePath,
            err,
          );
        }
      }
    };

    void sync();
  }, [files, status]);

  // Reset when disabled
  useEffect(() => {
    if (!enabled) {
      hasStartedRef.current = false;
      syncedRef.current.clear();
      setStatus("idle");
      setPreviewUrl(null);
      setError(null);
    }
  }, [enabled]);

  // Manually Restart the entire WebContainer process
  const restart = useCallback(() => {
    (async () => {
      // Teardown and terminate the active WebContainer instance and its running processes
      await teardownWebContainer();
      // Clear the current container reference stored in the ref
      containerRef.current = null;
      // Reset the start guard flag back to false to permit a fresh boot sequence
      hasStartedRef.current = false;
      // Clear sync bookkeeping so the next mount reseeds it correctly
      syncedRef.current.clear();
      // Reset the container lifecycle status back to "idle"
      setStatus("idle");
      // Clear the live preview URL state
      setPreviewUrl(null);
      // Clear any existing error messages from previous attempts
      setError(null);
      // Increment the restart key state counter to trigger dependent effects and re-initialize
      setRestartKey((k) => k + 1);
    })();
  }, []);

  return {
    status,
    previewUrl,
    error,
    restart,
    terminalOutput,
    reloadKey,
  };
};
